source 'http://rubygems.org'

gem 'rails', '2.3.5'
gem 'mysql2', '< 0.3'
gem 'warden'
gem 'devise', '1.0.11'
gem 'will_paginate', '~> 2.0'
gem 'settingslogic'                                                             
gem 'fastercsv'                                                                 
gem 'rest-client'                                                               
gem 'mechanize'                                                                 
gem 'json'
