production:
 create_from_remote: no
 use.user.selected.activities: yes

development:
 encounter_privilege_map: Diabetes history:Manage diabetes history,Diabetes initial questions:Manage diabetes initial questions,Diabetes test:Manage diabetes tests,General health:Manage General health,Past diabetes medical history:Manage past diabetes medical history,Update hiv status:Manage HIV Status Visits,Lab results:Manage Lab Results,Vitals:Manage Vitals,Give drugs:Manage Give Drugs,Lab orders:Manage Lab Orders
 dc.number.prefix: QECH
 application_generic_medication: Diabetes medication
 create_from_remote: no
 use.user.selected.activities: false
 vitals.blood_pressure: true
 advanced.prescription.interface: true
 auto_set_appointment: true

test: &TEST
 create_from_remote: no
 use.user.selected.activities: yes

cucumber:
  <<: *TEST
