production:
 create_from_remote: no
 use.user.selected.activities: yes

development:
 dc.number.prefix: QECH
 application_generic_medication: Diabetes medication
 create_from_remote: no
 use.user.selected.activities: false
 vitals.blood_pressure: true
 advanced.prescription.interface: true

test: &TEST
 create_from_remote: no
 use.user.selected.activities: yes

cucumber:
  <<: *TEST
