production:
 create.from.remote: false
 create.from.dde.server: false
 use.user.selected.activities: no
 filing.number.prefix: FN101,FN102
 auto_set_appointment: true
 records_per_page: 15
 debugger_sorting_attribute: arv_number

development:
 create.from.remote: false
 create.from.dde.server: false
 use.user.selected.activities: no
 filing.number.prefix: FN101,FN102
 auto_set_appointment: true
 show.patient.confirmation: false
 records_per_page: 15
 debugger_sorting_attribute: arv_number

test: &TEST
 create_from_remote: no
 use.user.selected.activities: yes

cucumber:
  <<: *TEST
