production:
  adapter: mysql2
  username: root
  database: openmrs_dmht_live #openmrs_kch
  password: password #root
  host: localhost #192.168.11.147
  pool: 500

development:
  adapter: mysql2
  username: root
  database: openmrs_dmht_live #openmrs_kch
  password: password #root
  host: localhost #192.168.11.147
  pool: 500

test: &TEST
  adapter: mysql
  database: root
  username: bart2_db
  password: your_password
  host: localhost

cucumber:
  <<: *TEST
