--- 
cwd: /var/www/apzu/patient_registration/
log_file: /var/www/apzu/patient_registration/log/mongrel.log
port: 8000
environment: production
address: 127.0.0.1
pid_file:  /var/www/apzu/patient_registration/tmp/pids/mongrel.pid
servers: 3 
